#include "Libs/unity/src/unity.h"
#include "calculatorFunc.h"
#define DECIMAL_PRECISSION 2
void test_addtion_diffrent_typ_of_values(void)
{
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 8, addtion(5, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, addtion(0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, addtion(-0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, -4, addtion(-2, -2));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 1, addtion(-2, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 5.5, addtion(2.1, 3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, -5.5, addtion(-2.1, -3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 3000000, addtion(1000000, 2000000));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, -3000000, addtion(-1000000, -2000000));
}

void test_subtraction_diffrent_typ_of_values(void)
{
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 2, subtraction(5, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, subtraction(0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, subtraction(-0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, subtraction(-2, -2));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,-5, subtraction(-2, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,-1.3, subtraction(2.1, 3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,1.3, subtraction(-2.1, -3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,-1000000, subtraction(1000000, 2000000));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,1000000, subtraction(-1000000, -2000000));
}

void test_multiplication_diffrent_typ_of_values(void)
{
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 15, multiplication(5, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, multiplication(0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, multiplication(-0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 4, multiplication(-2, -2));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,-6, multiplication(-2, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,7.14, multiplication(2.1, 3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,7.14, multiplication(-2.1, -3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,2000000000000, multiplication(1000000, 2000000));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION,2000000000000, multiplication(-1000000, -2000000));
}

void test_division_diffrent_typ_of_values(void)
{
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 1.66, division(5, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, division(0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0, division(-0,0));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 1, division(-2, -2));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, -0.66, division(-2, 3));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0.61, division(2.1, 3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0.61, division(-2.1, -3.4));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0.5, division(1000000, 2000000));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 0.5, division(-1000000, -2000000));
TEST_ASSERT_FLOAT_WITHIN(DECIMAL_PRECISSION, 5, division(10, 2));
}

int main(void)
{
UNITY_BEGIN();
RUN_TEST(test_addtion_diffrent_typ_of_values);
RUN_TEST(test_subtraction_diffrent_typ_of_values);
RUN_TEST(test_multiplication_diffrent_typ_of_values);
RUN_TEST(test_division_diffrent_typ_of_values);
return UNITY_END();
}
